In [4]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [11]:
#int
i = 1145
print(i,'\t',type(i))
#float
f = 3.14
print(f,'\t',type(f))
#str
s = 'python'
print(s,'\t',type(s))
#bool
b = 3>2
print(b,'\t',type(b))

1145 	 <class 'int'>
3.14 	 <class 'float'>
python 	 <class 'str'>
True 	 <class 'bool'>


In [19]:
#转义字符
print('t\\nst')    #t\nst

t\nst


In [23]:
#类型转换
n = 3.0
print(n,type(n))
str_n = str(n)
print(str_n,type(str_n))
f_n = float(n)
print(f_n,type(f_n))

3.0 <class 'float'>
3.0 <class 'str'>
3.0 <class 'float'>


In [24]:
#缩进
a = 300
if(a>200):
    print("MOSC")
    print("a>200")

MOSC
a>200


In [32]:
# **			求幂
# //、%		整除、求模
# >、<、>=、<=、==、!=
# and、or、not	或与非 && || 
print(2**3)
print(3//2)
print(4%2)
a = 100
if(a>10 or a<9):
    print("MOSClny")

8
1
0
MOSClny


In [36]:
#占位符

n = 2021.12745
name = "%s is %.2f"%("Year",n)
print(name)

Year is 2021.13


In [40]:
#列表
l = [1,2,3,4,5]
print(type(l))
print(len(l))
print(l)

<class 'list'>
5
[1, 2, 3, 4, 5]


In [45]:
information = ["lny",100,100,100,True]
for x in information:
    print(x)

lny
100
100
100
True


In [46]:
information.append("ybb")
print(information)

['lny', 100, 100, 100, True, 'ybb']


In [55]:
information.insert(0,"MOSC")
print(information)

['MOSC', 'lny', 100, 100, 100, True]


In [56]:
information.insert(1,"CEO")

In [49]:
print(information)

['MOSC', 'CEO', 'lny', 100, 100, 100, True, 'ybb']


In [50]:
for x in information:
    print(x,type(x))

MOSC <class 'str'>
CEO <class 'str'>
lny <class 'str'>
100 <class 'int'>
100 <class 'int'>
100 <class 'int'>
True <class 'bool'>
ybb <class 'str'>


In [51]:
#del/pop/remove
del information[1]

In [52]:
for x in information:
    print(x,type(x))

MOSC <class 'str'>
lny <class 'str'>
100 <class 'int'>
100 <class 'int'>
100 <class 'int'>
True <class 'bool'>
ybb <class 'str'>


In [59]:
# information.pop(0)
# print(information.pop(0))
print(information)


['CEO', 'lny', 100, 100, 100, True]


In [62]:
#remove按值移除
information.remove(100)
print(information)

['CEO', 'lny', 100, True]


In [71]:
information = ["lny","100","100","10",[122,1112,2]]
print(information)
for x in information:
    print(x,type(x))

['lny', '100', '100', '10', [122, 1112, 2]]
lny <class 'str'>
100 <class 'str'>
100 <class 'str'>
10 <class 'str'>
[122, 1112, 2] <class 'list'>


In [72]:
numbers = [x for x in range(10)] //numbers[x:y:z]
print(numbers)
print(numbers[3:9])
print(numbers[3:])
print(numbers[:9])
print(numbers[-6:-1])//-6+10 = 4 -1+10=9 =>print(numbers[4:9])
print(numbers[1:9:2])
print(numbers[-1:1:-2])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[3, 4, 5, 6, 7, 8]
[3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[4, 5, 6, 7, 8]
[1, 3, 5, 7]
[9, 7, 5, 3]


In [73]:
#dict
lny = [('java',90),('DS',80),("PE",60)]
lnyDict = dict(lny)
print(lnyDict)

{'java': 90, 'DS': 80, 'PE': 60}


In [74]:
print(len(lnyDict))

3


In [75]:
print(lnyDict['java'])

90


In [76]:
lnyDict['java'] = 1000
print(lnyDict['java'])

1000


In [77]:
print(lnyDict)

{'java': 1000, 'DS': 80, 'PE': 60}


In [78]:
lnyDict['Eng'] = 10
print(lnyDict)

{'java': 1000, 'DS': 80, 'PE': 60, 'Eng': 10}


In [79]:
del lnyDict['Eng']
print(lnyDict)

{'java': 1000, 'DS': 80, 'PE': 60}


In [88]:
#function
def repeat(n,m):
    for i in range(m):
        print(n)
    return n,m

a,b = repeat(3.14,5) #a,b=n,m
print(a,b)

3.14
3.14
3.14
3.14
3.14
3.14 5


In [91]:
#eval
s = eval("3+2+1+5") # s = 3+2+1+5
print(s)

11


In [94]:
#lambda
sum = lambda a,b:a+b
print(sum(10,20))

30


In [95]:
#for
Bot = ['Bot1','Bot2','Bot3']
for x in Bot:
    print(x)

Bot1
Bot2
Bot3


In [99]:
for x in range(10):#for(int i = 0; i<10;i++)
    print(x)

4
6
8


In [102]:
a = 100
if(a>200):
    print("a>200")
elif (a==100):         #else if
    print("a==100")
else:
    print("a<200")

a==100


In [103]:
import torch

In [105]:
#tensor张量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [106]:
x.shape

torch.Size([12])

In [109]:
x = x.reshape(3,4)
x.shape

torch.Size([3, 4])

In [110]:
x.numel()

12

In [111]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [112]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [116]:
torch.rand(3,4)      #rand

tensor([[0.5099, 0.2150, 0.1256, 0.9562],
        [0.6222, 0.7884, 0.5195, 0.9951],
        [0.9690, 0.2396, 0.9229, 0.2433]])

In [117]:
torch.normal(torch.arange(1.0,11),torch.arange(1,0,-0.1))

tensor([2.2823, 1.7740, 3.5007, 3.1790, 4.8978, 5.5144, 7.5778, 7.8335, 8.8698,
        9.8480])

In [118]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [120]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x+y,x-y,x*y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
#连结concatenate
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
print(torch.cat((x,y),dim=0))